const AboutUs = () => {
    return (
        <>
            <h1>About us</h1>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam bibendum facilisis libero a fermentum. Nullam elementum hendrerit ante, sit amet rutrum sapien facilisis non. Maecenas blandit semper nulla in fermentum. Quisque mattis interdum eleifend. Nullam non elit pretium, condimentum arcu eget, rutrum ipsum. Maecenas ultricies, sem ut ornare fringilla, quam augue auctor sapien, vel vestibulum mi lacus et dolor. Mauris sed tempor orci, at mattis nibh. In egestas ultricies nulla eget fringilla. In ac consectetur ante. Nulla dictum at mauris et elementum. Donec interdum mi est, ac eleifend diam lacinia tempor. Nulla a gravida nulla. Donec euismod et ex at pellentesque. Aenean nisi metus, fringilla vel justo eu, cursus luctus orci. Nunc et pulvinar velit. Nullam blandit efficitur mauris, ac molestie velit vestibulum in.
                Morbi suscipit, augue at euismod pretium, mi orci imperdiet neque, ac interdum diam lorem et massa. Aliquam maximus tempus nisl, non cursus libero blandit ut. Curabitur consequat libero at massa lobortis, vel tempus tellus rutrum. Etiam malesuada ligula sit amet leo vehicula vestibulum. Nunc urna diam, ultricies a neque porta, lacinia efficitur leo. Nam non tortor volutpat, pretium purus at, imperdiet velit. Maecenas consequat, urna vel laoreet posuere, velit ipsum fringilla tortor, ut finibus turpis quam in ex. Fusce augue lacus, tempus quis velit sit amet, semper imperdiet sem. Praesent tincidunt varius magna. Vestibulum sed ultrices nulla. Suspendisse ullamcorper ligula quis interdum consequat. Aliquam venenatis consequat accumsan. In sit amet commodo tortor. Proin finibus, magna id tincidunt imperdiet, arcu urna placerat quam, in cursus erat tellus vitae neque.
                Aliquam et sagittis lorem. Maecenas molestie sem sit amet pellentesque volutpat. Pellentesque et convallis lorem. Proin volutpat eros nec purus dictum vulputate. Sed cursus congue justo sit amet pretium. Sed non odio vehicula, gravida metus sit amet, ornare risus. Pellentesque varius in enim sit amet tincidunt. Curabitur ante nulla, interdum nec ex sit amet, egestas porta elit. Sed id urna dictum, tincidunt tortor et, pharetra ex. Donec tempor ullamcorper ex, sed tempus erat aliquam sed. Nullam quis lectus vel justo faucibus auctor non eget eros.
                Aliquam vitae quam euismod, lacinia magna a, faucibus arcu. Nunc orci quam, fermentum condimentum pharetra quis, scelerisque vitae turpis. Vivamus feugiat non eros non gravida. Mauris interdum tellus at semper sodales. Ut et aliquam augue. Duis laoreet, sapien sit amet pharetra suscipit, neque velit gravida odio, non bibendum ligula purus non ex. Sed suscipit bibendum orci a aliquam. Suspendisse tempor massa quis quam sollicitudin lacinia. Nam vestibulum, neque ut porta auctor, orci eros vestibulum ipsum, id convallis sapien neque sed nunc. Phasellus ultricies scelerisque lectus, ac auctor ex rhoncus quis. Integer ut vehicula leo. Proin posuere, metus quis hendrerit finibus, nisi dolor interdum urna, nec iaculis massa orci et neque. Pellentesque luctus purus eget porta mattis. Integer aliquet tellus at accumsan luctus.
            </p>
        </>
    )
}

export default AboutUs